version: "2.1"

networks:
   appnetwork:
      driver: bridge

services:
   zookeeper:
      image: confluentinc/cp-zookeeper:latest
      networks:
         - appnetwork
      environment:
         ZOOKEEPER_CLIENT_PORT: 2181
         ZOOKEEPER_TICK_TIME: 2000
      ports:
         - 22181:2181

   kafka:
      image: confluentinc/cp-kafka:latest
      networks:
         - appnetwork
      depends_on:
         - zookeeper
      ports:
         - ${HOST_IP}:9092:9092
      environment:
         KAFKA_BROKER_ID: 0
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP}:9092
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
         KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

   kafka-ui:
      image: ghcr.io/kafbat/kafka-ui:latest
      networks:
         - appnetwork
      ports:
         - 8082:8080
      environment:
         DYNAMIC_CONFIG_ENABLED: "true"
         KAFKA_CLUSTERS_0_NAME: atha-robot
         KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      depends_on:
         - kafka
